name: Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    permissions:
      contents: read
    uses: dustfeather/shared-workflows/.github/workflows/node-test.yml@v1
